spring:
  application:
    name: "configserver"
  profiles:
    active: git
  cloud:
    config:
      server:
        git:
          uri: "https://github.com/seulee0862/microservice.git"
          default-label: section6
          timeout: 5
          clone-on-start: true
          force-pull: true
      #      server:
      #        native:
      #          search-locations: "classpath:/config"
      #          search-locations: "file:////Users//iseunghyeon//Documents//etc//config"

encrypt:
  key: "ASJDKHWQDJHJ@HDK12NQKF41"

server:
  port: 8071